<h1>PART-1</h1>

<h1>TASK-1</h1>

In [32]:
import numpy as np

In [33]:
rng = np.random.default_rng(seed=0)

In [34]:
readings = rng.normal(50, 10, size=(360,4))

print(readings.shape)

print(readings.dtype)

print(readings[:3])

(360, 4)
float64
[[51.25730221 48.67895137 56.4042265  51.04900117]
 [44.64330627 53.61595055 63.04000045 59.47080963]
 [42.96264764 37.34578529 43.76725537 50.41325979]]


<h2>TASK-2</h2>

In [35]:
scaled_readings = (readings -  readings.min())/(readings.max() -  readings.min())
scaled_readings

array([[0.57787323, 0.54085699, 0.65176534, 0.57488274],
       [0.48291902, 0.61173529, 0.7470322 , 0.69579091],
       [0.45879055, 0.37815174, 0.47034194, 0.56575568],
       ...,
       [0.4688222 , 0.60237252, 0.52284171, 0.36354375],
       [0.55606748, 0.78891062, 0.84731738, 0.47841507],
       [0.68978896, 0.57884936, 0.60057904, 0.74177356]], shape=(360, 4))

In [36]:
scaled_readings.max()

np.float64(1.0)

In [37]:
scaled_readings.min()

np.float64(0.0)

In [38]:
scaled_readings.mean(axis=0)

array([0.55746211, 0.54979789, 0.5508211 , 0.57424907])

In [39]:
centered_readings = readings  -  readings.mean(axis=0)

centered_readings

array([[  1.42172772,  -0.62277474,   7.03122873,   0.04413789],
       [ -5.19226822,   4.31422444,  13.66700268,   8.46594635],
       [ -6.87292684, -11.95594082,  -5.6057424 ,  -0.59160349],
       ...,
       [ -6.17417646,   3.66206427,  -1.94889261, -14.67659142],
       [ -0.09714235,  16.6552983 ,  20.6523254 ,  -6.67527788],
       [  9.21717155,   2.02356844,   3.46586852,  11.66884885]],
      shape=(360, 4))

<h1>TASK-3</h1>

In [40]:
outlier_mask = (readings > 80) | (readings < 20)


outlier_mask.sum()

(outlier_mask.sum()/readings.size)*100

np.float64(0.3472222222222222)

In [41]:
cleaned_readings = readings.astype(float).copy()

cleaned_readings[outlier_mask] = np.nan
cleaned_readings

array([[51.25730221, 48.67895137, 56.4042265 , 51.04900117],
       [44.64330627, 53.61595055, 63.04000045, 59.47080963],
       [42.96264764, 37.34578529, 43.76725537, 50.41325979],
       ...,
       [43.66139802, 52.96379038, 47.42410516, 36.32827186],
       [49.73843213, 65.95702441, 70.02532317, 44.3295854 ],
       [59.05274604, 51.32529455, 52.8388663 , 62.67371213]],
      shape=(360, 4))

In [42]:
np.isnan(cleaned_readings).sum()

np.int64(5)

<h1>TASK-4</h1>

In [43]:
sensor_means = np.array(readings.mean(axis=0))
sensor_stds = np.array(readings.std(axis=0))

time_means = np.array(readings.mean(axis=1))
time_means.shape
sensor_means.shape

(4,)

<h1>TASK-5</h1>

In [44]:


report = {"total_readings" : readings.size, "outlier_count" : int(np.isnan(cleaned_readings).sum()), "outlier_percent" : (int(np.isnan(cleaned_readings).sum())/outlier_mask.size)*100 ,"sensor_means" : sensor_means , "sensor_stds" :sensor_stds}


#Report

for key,value in report.items():
    print(key,value)

report["total_readings"] == readings.size


total_readings 1440
outlier_count 5
outlier_percent 0.3472222222222222
sensor_means [49.83557449 49.30172611 49.37299777 51.00486328]
sensor_stds [ 9.74752295  9.59309985  9.99833748 10.18720053]


True

<h1>PART-2</h1>
<h1>TASK-6</h1>

In [45]:
rng = np.random.default_rng(seed=0)

sim = np.array(rng.normal(0,1,size=(1000,6)))

print(sim.shape)


print(sim.dtype)

print(sim[:3])

(1000, 6)
float64
[[ 0.12573022 -0.13210486  0.64042265  0.10490012 -0.53566937  0.36159505]
 [ 1.30400005  0.94708096 -0.70373524 -1.26542147 -0.62327446  0.04132598]
 [-2.32503077 -0.21879166 -1.24591095 -0.73226735 -0.54425898 -0.31630016]]


<h1>TASK-7</h1>

In [46]:
scenario_shift = np.array([-0.3, -0.1, 0.0, 0.1, 0.2, 0.4])


adjusted_sim = sim + scenario_shift

adjusted_sim.shape == sim.shape

adjusted_sim_mean = adjusted_sim.mean(axis=0)

sim_means = sim.mean(axis=0)

print(sim_means - adjusted_sim_mean)

[ 0.3  0.1  0.  -0.1 -0.2 -0.4]


<h1>TASK-8</h1>

In [60]:
scenario_means = np.array(adjusted_sim.mean(axis=0))

np.argsort(scenario_means)

top_2 = np.partition(scenario_means,-2)


top_2[-2:]

array([0.19477725, 0.39966337])

<h1>TASK-9</h1>

In [61]:
rng_2 = np.random.default_rng(seed=0)

sim_2 = np.array(rng_2.normal(0,1,size=(1000,6)))

rng_3 = np.random.default_rng(seed=1)

sim_3 = np.array(rng_3.normal(0,1,size=(1000,6)))
sim_2.shape == sim_3.shape

np.allclose(sim_2, sim_3)

top_two_values = top_2[-2:]

c_scenario_means = scenario_means.copy()

c_scenario_means = c_scenario_means.tolist()

top_two_indices = [c_scenario_means.index(value) for value in top_two_values]

scenario_means[top_two_indices]

array([0.19477725, 0.39966337])

<h1>TASK-10</h1>

In [63]:


report = {
    "shape": adjusted_sim.shape,
    "scenario_means": scenario_means,
    "top_two_indices": top_two_indices,
    "top_two_values": top_two_values.tolist()
}

assert len(scenario_means) == 6, "scenario_means should have length 6"
assert len(top_two_indices) == 2, "top_two_indices should have length 2"


report_string = (
    f"Simulation Shape: {report['shape']}\n"
    f"Scenario Means: {report['scenario_means']}\n"
    f"Top Two Scenario Indices: {report['top_two_indices']}\n"
    f"Top Two Scenario Values: {report['top_two_values']}"
)

print(report_string)

Simulation Shape: (1000, 6)
Scenario Means: [-0.33621381 -0.04969297  0.01921678  0.0638128   0.19477725  0.39966337]
Top Two Scenario Indices: [4, 5]
Top Two Scenario Values: [0.19477724824360756, 0.399663366342199]
